# Generated by Django 6.0.2 on 2026-03-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatusChoices',
            fields=[
                ('status', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with_me', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.contactstatuschoices')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'email'), name='unique_contact_email_per_owner', violation_error_message='You already have contact with the provided email'), models.UniqueConstraint(fields=('owner', 'phone_number'), name='unique_contact_phone_number_per_owner', violation_error_message='You already have contact with the provided phone number')],
            },
        ),
    ]
